// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB82o7KedARO1l6agE3ZcwlTueQx9p-uos',
    appId: '1:521086661246:web:3da683a8f0a3c1bc9c9e2f',
    messagingSenderId: '521086661246',
    projectId: 'zwigzo-food',
    authDomain: 'zwigzo-food.firebaseapp.com',
    storageBucket: 'zwigzo-food.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCklsF9BJbMJAFNRJFararMY8iFw8Yy8iY',
    appId: '1:521086661246:android:ff10a97fb0c2622a9c9e2f',
    messagingSenderId: '521086661246',
    projectId: 'zwigzo-food',
    storageBucket: 'zwigzo-food.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqCtXoCh6tDyxOjdMKe4unGT_5W5qSb14',
    appId: '1:521086661246:ios:80473d9afb6b47b09c9e2f',
    messagingSenderId: '521086661246',
    projectId: 'zwigzo-food',
    storageBucket: 'zwigzo-food.appspot.com',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqCtXoCh6tDyxOjdMKe4unGT_5W5qSb14',
    appId: '1:521086661246:ios:124fb435ca980cae9c9e2f',
    messagingSenderId: '521086661246',
    projectId: 'zwigzo-food',
    storageBucket: 'zwigzo-food.appspot.com',
    iosBundleId: 'com.example.foodapp.RunnerTests',
  );
}
